apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  labels:
    app: common
    group: org.demo
    provider: fabric8
    version: 1.0.0
  name: common-s2i
spec:
  failedBuildsHistoryLimit: 5
  output:
    to:
      kind: ImageStreamTag
      name: common:1.0.0
  postCommit: {}
  resources: {}
  runPolicy: Serial
  source:
    git:
      uri: https://github.com/greenpeace-hack/common.git
    type: Git
  strategy:
    sourceStrategy:
      from:
        kind: ImageStreamTag
        name: fuse7-java-openshift:1.1
        namespace: openshift
    type: Source
  successfulBuildsHistoryLimit: 5
  triggers: []
